export type Destination = {
  slug: string;
  name: string;
  code: string; // IATA-style code
  city: string;
  flag: string;
  tagline: string;
  blurb: string;
  intro: string;
  stats: { label: string; value: string }[];
  highlights: { title: string; text: string }[];
  intakes: string;
  popularCourses: string[];
  visa: string;
  workRights: string;
};

export const destinations: Destination[] = [
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    code: "LHR",
    city: "London",
    flag: "🇬🇧",
    tagline: "Centuries of prestige, one year to a master's.",
    blurb: "World-heritage universities, 1-year master's, post-study work visas.",
    intro:
      "Home to some of the oldest and most respected universities on earth, the UK pairs academic tradition with fast, focused degrees. A one-year master's gets you qualified — and into the workforce — sooner.",
    stats: [
      { label: "Universities", value: "130+" },
      { label: "Master's length", value: "1 yr" },
      { label: "Post-study visa", value: "2 yrs" },
      { label: "Intl. students", value: "600k+" },
    ],
    highlights: [
      { title: "Graduate Route Visa", text: "Stay and work for 2 years after graduating (3 for PhDs)." },
      { title: "Fast degrees", text: "Most master's take just 12 months — less tuition, sooner earning." },
      { title: "Global reputation", text: "Oxford, Cambridge, Imperial, UCL and more sit in the world top 20." },
    ],
    intakes: "September & January",
    popularCourses: ["Business & Management", "Data Science", "Law", "Engineering", "Public Health"],
    visa: "Student visa (Tier 4) — we prepare your CAS, finances and interview.",
    workRights: "20 hrs/week during term, full-time in holidays.",
  },
  {
    slug: "united-states",
    name: "United States",
    code: "JFK",
    city: "New York",
    flag: "🇺🇸",
    tagline: "The world's deepest bench of research and opportunity.",
    blurb: "Unmatched research, flexible curricula, generous scholarships.",
    intro:
      "The USA offers unrivalled breadth: thousands of universities, flexible majors you can shape as you go, and research funding that dwarfs the rest of the world. Ambition has a home here.",
    stats: [
      { label: "Universities", value: "200+" },
      { label: "OPT work", value: "3 yrs" },
      { label: "Scholarships", value: "Huge" },
      { label: "Intl. students", value: "1M+" },
    ],
    highlights: [
      { title: "STEM OPT", text: "STEM grads can work up to 3 years after study on OPT." },
      { title: "Flexible majors", text: "Explore before you commit — switch or combine fields freely." },
      { title: "Funding", text: "Assistantships and merit aid can cover much of your tuition." },
    ],
    intakes: "Fall (Aug) & Spring (Jan)",
    popularCourses: ["Computer Science", "Business (MBA)", "Engineering", "Finance", "Design"],
    visa: "F-1 student visa — we coach you through the DS-160 and consular interview.",
    workRights: "On-campus during study; CPT/OPT for off-campus work.",
  },
  {
    slug: "canada",
    name: "Canada",
    code: "YYZ",
    city: "Toronto",
    flag: "🇨🇦",
    tagline: "A clear runway from study to permanent residency.",
    blurb: "Affordable tuition, welcoming immigration, clear PR pathways.",
    intro:
      "Canada is the pragmatic dream: high-quality education at a fair price, a genuinely welcoming immigration system, and one of the world's clearest pathways from student to permanent resident.",
    stats: [
      { label: "Universities", value: "90+" },
      { label: "PGWP", value: "3 yrs" },
      { label: "PR pathway", value: "Clear" },
      { label: "Intl. students", value: "800k+" },
    ],
    highlights: [
      { title: "Post-Graduation Work Permit", text: "Work up to 3 years after graduating — a direct route to PR." },
      { title: "Affordable", text: "Lower tuition and living costs than the US, UK or Australia." },
      { title: "Quality of life", text: "Safe, multicultural cities that consistently top livability rankings." },
    ],
    intakes: "Fall, Winter & Summer",
    popularCourses: ["Business", "Health Sciences", "IT & Software", "Engineering", "Hospitality"],
    visa: "Study permit — we build your SOP, proof of funds and GIC.",
    workRights: "Up to 24 hrs/week off-campus during term.",
  },
  {
    slug: "australia",
    name: "Australia",
    code: "SYD",
    city: "Sydney",
    flag: "🇦🇺",
    tagline: "World-class study under the sun.",
    blurb: "Global rankings, sunshine campuses, strong work rights.",
    intro:
      "Australia blends top-100 universities with an outdoor, high-quality lifestyle and some of the strongest post-study work rights anywhere — all on the world's most livable continent.",
    stats: [
      { label: "Universities", value: "40+" },
      { label: "Work visa", value: "2–4 yrs" },
      { label: "Top 100 unis", value: "7" },
      { label: "Intl. students", value: "700k+" },
    ],
    highlights: [
      { title: "Temporary Graduate Visa", text: "Stay and work 2–4 years depending on your qualification." },
      { title: "Group of Eight", text: "Australia's elite research universities rank among the world's best." },
      { title: "Lifestyle", text: "Beaches, safety and vibrant student cities like Melbourne & Sydney." },
    ],
    intakes: "February & July",
    popularCourses: ["Nursing & Health", "Engineering", "IT", "Accounting", "Environmental Science"],
    visa: "Subclass 500 student visa — we handle GTE, OSHC and finances.",
    workRights: "48 hrs/fortnight during term, unlimited in breaks.",
  },
  {
    slug: "ireland",
    name: "Ireland",
    code: "DUB",
    city: "Dublin",
    flag: "🇮🇪",
    tagline: "Europe's English-speaking tech gateway.",
    blurb: "Tech & pharma hub, English-speaking, 2-year stay-back visa.",
    intro:
      "Ireland is the European HQ for the world's biggest tech and pharma companies — and it's English-speaking. A warm culture, strong graduate visa, and a direct line into global employers.",
    stats: [
      { label: "Universities", value: "30+" },
      { label: "Stay-back", value: "2 yrs" },
      { label: "Tech HQs", value: "1000+" },
      { label: "Intl. students", value: "35k+" },
    ],
    highlights: [
      { title: "Third Level Graduate Visa", text: "Stay up to 2 years after a master's to work in Ireland." },
      { title: "Global employers", text: "Google, Apple, Meta, Pfizer and more base their EU HQ here." },
      { title: "English-speaking EU", text: "Access the EU while studying and living in English." },
    ],
    intakes: "September & January",
    popularCourses: ["Computer Science", "Pharmaceuticals", "Business Analytics", "Finance", "Biotech"],
    visa: "Irish student visa (Stamp 2) — we manage finances and enrolment proof.",
    workRights: "20 hrs/week during term, 40 hrs in holidays.",
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    code: "AKL",
    city: "Auckland",
    flag: "🇳🇿",
    tagline: "Small country, world-class degrees, big outdoors.",
    blurb: "All-public universities in the top 3%, safe, generous work rights.",
    intro:
      "Every one of New Zealand's eight universities ranks in the world's top 3%. Add a famously safe, outdoor lifestyle and a straightforward post-study work visa, and you have one of the most balanced study destinations on earth.",
    stats: [
      { label: "Universities", value: "8" },
      { label: "Post-study work", value: "3 yrs" },
      { label: "Global top 3%", value: "All 8" },
      { label: "Intl. students", value: "70k+" },
    ],
    highlights: [
      { title: "Post-Study Work Visa", text: "Work up to 3 years after graduating, open to any employer." },
      { title: "Safe & welcoming", text: "Consistently ranked among the safest, most peaceful countries." },
      { title: "Quality guaranteed", text: "All eight universities are public and internationally ranked." },
    ],
    intakes: "February & July",
    popularCourses: ["Agriculture & Environment", "IT", "Engineering", "Business", "Film & Design"],
    visa: "Fee-paying student visa — we prepare funds, health and enrolment proof.",
    workRights: "20 hrs/week during term, full-time in scheduled breaks.",
  },
  {
    slug: "germany",
    name: "Germany",
    code: "FRA",
    city: "Frankfurt",
    flag: "🇩🇪",
    tagline: "Engineering excellence — often tuition-free.",
    blurb: "Low-to-no tuition, engineering powerhouse, EU opportunities.",
    intro:
      "Germany is Europe's engineering and innovation engine — and public universities often charge little to no tuition. Study in English, graduate debt-light, and step into the EU job market.",
    stats: [
      { label: "Universities", value: "60+" },
      { label: "Public tuition", value: "€0" },
      { label: "Job-seeker visa", value: "18 mo" },
      { label: "Intl. students", value: "450k+" },
    ],
    highlights: [
      { title: "Little to no tuition", text: "Most public universities charge only a small semester fee." },
      { title: "Job-seeker visa", text: "Stay 18 months after graduating to find work in Germany." },
      { title: "Engineering & tech", text: "Home to global leaders in automotive, robotics and research." },
    ],
    intakes: "Winter (Oct) & Summer (Apr)",
    popularCourses: ["Mechanical Engineering", "Computer Science", "Automotive", "Data Science", "Physics"],
    visa: "German student visa — we prepare your blocked account and APS.",
    workRights: "120 full or 240 half days per year.",
  },
  {
    slug: "france",
    name: "France",
    code: "CDG",
    city: "Paris",
    flag: "🇫🇷",
    tagline: "Grande écoles, low tuition, life in the heart of Europe.",
    blurb: "Affordable public tuition, elite business schools, 2-year job search.",
    intro:
      "France combines heavily subsidised public tuition with some of the world's most prestigious business and engineering schools. A growing range of English-taught programmes and a two-year job-search visa make it a serious contender.",
    stats: [
      { label: "Universities", value: "70+" },
      { label: "Public tuition", value: "Low" },
      { label: "Job-search visa", value: "2 yrs" },
      { label: "Intl. students", value: "400k+" },
    ],
    highlights: [
      { title: "APS job-search visa", text: "Master's grads can stay up to 2 years to find work or start a business." },
      { title: "Elite schools", text: "HEC, INSEAD, École Polytechnique and other world leaders call France home." },
      { title: "Affordable living", text: "Generous student housing aid (CAF) and subsidised transport and meals." },
    ],
    intakes: "September & January",
    popularCourses: ["Business & Management", "Luxury & Fashion", "Engineering", "Culinary Arts", "International Relations"],
    visa: "VLS-TS student visa via Campus France — we guide the full Études en France process.",
    workRights: "Up to 964 hrs/year (about 20 hrs/week).",
  },
  {
    slug: "italy",
    name: "Italy",
    code: "FCO",
    city: "Rome",
    flag: "🇮🇹",
    tagline: "The world's oldest universities, remarkably affordable.",
    blurb: "Low tuition, income-based fees, design and heritage on your doorstep.",
    intro:
      "Italy is home to the oldest university in the world and some of Europe's best value degrees, with tuition often scaled to family income. Study design, engineering or the humanities surrounded by living history.",
    stats: [
      { label: "Universities", value: "90+" },
      { label: "Tuition", value: "Income-based" },
      { label: "Post-study visa", value: "12 mo" },
      { label: "Intl. students", value: "130k+" },
    ],
    highlights: [
      { title: "Income-based tuition", text: "Public university fees are scaled to family income — often very low." },
      { title: "Design & fashion", text: "Milan and Florence are global capitals of design, fashion and architecture." },
      { title: "Regional scholarships", text: "DSU regional grants can cover fees, meals and accommodation." },
    ],
    intakes: "September & February",
    popularCourses: ["Architecture & Design", "Fashion", "Engineering", "Fine Arts", "Food Science"],
    visa: "Italian study visa (Type D) — we prepare pre-enrolment on Universitaly and funds proof.",
    workRights: "Up to 20 hrs/week (1,040 hrs/year).",
  },
  {
    slug: "hungary",
    name: "Hungary",
    code: "BUD",
    city: "Budapest",
    flag: "🇭🇺",
    tagline: "Central-European quality at a fraction of the cost.",
    blurb: "Low tuition and living costs, EU degrees, famous medical schools.",
    intro:
      "Hungary offers accredited EU degrees — especially in medicine and engineering — at some of the lowest tuition and living costs in Europe. Budapest pairs a rich student culture with genuine affordability.",
    stats: [
      { label: "Universities", value: "60+" },
      { label: "Tuition", value: "Low" },
      { label: "EU degree", value: "Yes" },
      { label: "Intl. students", value: "40k+" },
    ],
    highlights: [
      { title: "Renowned medical schools", text: "Semmelweis and others train doctors recognised across the EU and beyond." },
      { title: "Low cost of living", text: "One of the most affordable capitals in the EU for students." },
      { title: "Stipendium scholarships", text: "Government scholarships cover tuition and a monthly stipend for many." },
    ],
    intakes: "September & February",
    popularCourses: ["Medicine & Dentistry", "Engineering", "Business", "Pharmacy", "Computer Science"],
    visa: "Hungarian student residence permit — we handle acceptance, funds and health cover.",
    workRights: "Up to 24 hrs/week during term (66 days full-time in breaks).",
  },
  {
    slug: "malaysia",
    name: "Malaysia",
    code: "KUL",
    city: "Kuala Lumpur",
    flag: "🇲🇾",
    tagline: "Global degrees in Asia — for a lot less.",
    blurb: "UK/Australian branch campuses, low costs, English-taught.",
    intro:
      "Malaysia hosts branch campuses of leading UK and Australian universities, so you can earn a globally recognised degree in English at a fraction of the cost — in one of Asia's most connected, multicultural hubs.",
    stats: [
      { label: "Universities", value: "70+" },
      { label: "Branch campuses", value: "Many" },
      { label: "Tuition", value: "Low" },
      { label: "Intl. students", value: "130k+" },
    ],
    highlights: [
      { title: "Foreign branch campuses", text: "Study Nottingham, Monash, Heriot-Watt and more — locally, for less." },
      { title: "Affordable & English", text: "Low tuition and living costs with English as the language of instruction." },
      { title: "Regional hub", text: "A springboard into fast-growing ASEAN economies and travel across Asia." },
    ],
    intakes: "February, July & September",
    popularCourses: ["Business", "Engineering", "IT & Computing", "Hospitality", "Actuarial Science"],
    visa: "Student Pass via EMGS — we manage the online application and medicals.",
    workRights: "Up to 20 hrs/week during breaks and holidays.",
  },
  {
    slug: "uae",
    name: "United Arab Emirates",
    code: "DXB",
    city: "Dubai",
    flag: "🇦🇪",
    tagline: "Western degrees, zero income tax, gateway to the world.",
    blurb: "International branch campuses, tax-free work, global business hub.",
    intro:
      "The UAE brings the world's universities to one tax-free, ultra-connected hub. Study at international branch campuses in Dubai and Abu Dhabi, then step straight into one of the fastest-growing business ecosystems on earth.",
    stats: [
      { label: "Universities", value: "70+" },
      { label: "Income tax", value: "0%" },
      { label: "Branch campuses", value: "Many" },
      { label: "Intl. students", value: "200k+" },
    ],
    highlights: [
      { title: "Global branch campuses", text: "NYU, Heriot-Watt, Wollongong, Birmingham and more operate here." },
      { title: "Tax-free earnings", text: "Keep 100% of what you earn — no personal income tax." },
      { title: "Career springboard", text: "A world business hub connecting Europe, Asia and Africa." },
    ],
    intakes: "September & January",
    popularCourses: ["Business & Finance", "Engineering", "Aviation", "IT", "Media & Design"],
    visa: "Student residence visa — typically sponsored by your university; we coordinate documents.",
    workRights: "Part-time work permitted with university and authority approval.",
  },
  {
    slug: "south-korea",
    name: "South Korea",
    code: "ICN",
    city: "Seoul",
    flag: "🇰🇷",
    tagline: "Where cutting-edge tech meets generous scholarships.",
    blurb: "Top Asian universities, big scholarships, tech and culture powerhouse.",
    intro:
      "South Korea pairs some of Asia's highest-ranked universities with generous scholarships and a tech-driven economy behind Samsung, Hyundai and LG. English-taught programmes and a post-study visa make it increasingly accessible.",
    stats: [
      { label: "Universities", value: "40+" },
      { label: "Scholarships", value: "Generous" },
      { label: "Post-study visa", value: "Yes" },
      { label: "Intl. students", value: "200k+" },
    ],
    highlights: [
      { title: "GKS & university scholarships", text: "Government and university awards can cover tuition plus living costs." },
      { title: "Tech economy", text: "Study beside the R&D engines of Samsung, Hyundai, LG and Naver." },
      { title: "D-10 job-seeker visa", text: "Graduates can switch to a job-seeking visa to find local work." },
    ],
    intakes: "March & September",
    popularCourses: ["Engineering", "Computer Science", "Business", "Korean Studies", "Media & Arts"],
    visa: "D-2 student visa — we prepare your certificate of admission and funds proof.",
    workRights: "Up to 20 hrs/week during term with a part-time work permit.",
  },
  {
    slug: "turkey",
    name: "Turkey",
    code: "IST",
    city: "Istanbul",
    flag: "🇹🇷",
    tagline: "Two continents, world-ranked universities, fully-funded options.",
    blurb: "Affordable tuition, generous state scholarships, East-meets-West.",
    intro:
      "Bridging Europe and Asia, Turkey offers rapidly rising, internationally ranked universities, low costs, and one of the world's most generous scholarship schemes — Türkiye Bursları — which funds tuition, housing and a stipend.",
    stats: [
      { label: "Universities", value: "200+" },
      { label: "Tuition", value: "Low" },
      { label: "Türkiye Bursları", value: "Full-ride" },
      { label: "Intl. students", value: "300k+" },
    ],
    highlights: [
      { title: "Türkiye Bursları", text: "A flagship scholarship covering tuition, accommodation, stipend and flights." },
      { title: "Affordable study", text: "Low tuition and living costs across historic, vibrant cities." },
      { title: "Strategic location", text: "A cultural and business bridge between Europe, Asia and the Middle East." },
    ],
    intakes: "September & February",
    popularCourses: ["Engineering", "Medicine", "Business", "Architecture", "International Relations"],
    visa: "Turkish student visa + residence permit — we guide acceptance and application.",
    workRights: "Postgraduate students may work part-time with a permit.",
  },
  {
    slug: "thailand",
    name: "Thailand",
    code: "BKK",
    city: "Bangkok",
    flag: "🇹🇭",
    tagline: "International degrees in the heart of Southeast Asia.",
    blurb: "Affordable international programmes, low living costs, ASEAN gateway.",
    intro:
      "Thailand's international universities deliver English-taught, globally recognised degrees at a fraction of Western costs — set in one of the world's most affordable, welcoming and well-connected regions.",
    stats: [
      { label: "Universities", value: "150+" },
      { label: "Intl. programmes", value: "Many" },
      { label: "Living cost", value: "Low" },
      { label: "Intl. students", value: "30k+" },
    ],
    highlights: [
      { title: "English-taught degrees", text: "Leading universities run international programmes fully in English." },
      { title: "Very low costs", text: "Among the most affordable places to live and study in Asia." },
      { title: "ASEAN gateway", text: "A central base for travel and careers across Southeast Asia." },
    ],
    intakes: "August & January",
    popularCourses: ["Business", "Hospitality & Tourism", "International Relations", "Engineering", "Communication Arts"],
    visa: "Non-Immigrant ED visa — we prepare your acceptance and supporting documents.",
    workRights: "Limited; internships and on-campus roles with university approval.",
  },
  {
    slug: "china",
    name: "China",
    code: "PEK",
    city: "Beijing",
    flag: "🇨🇳",
    tagline: "Elite universities and scholarships in a global superpower.",
    blurb: "World top-100 universities, major scholarships, English-taught options.",
    intro:
      "China is home to a growing cluster of world top-100 universities, extensive English-taught programmes, and some of the most generous scholarships available anywhere — an unmatched vantage point on the world's second-largest economy.",
    stats: [
      { label: "Universities", value: "300+" },
      { label: "Top 100 unis", value: "7+" },
      { label: "Scholarships", value: "Major" },
      { label: "Intl. students", value: "450k+" },
    ],
    highlights: [
      { title: "CSC scholarships", text: "Chinese Government Scholarships can cover tuition, housing and a stipend." },
      { title: "World top-100 unis", text: "Tsinghua, Peking, Fudan and others rank among the global elite." },
      { title: "English-taught degrees", text: "Thousands of programmes are delivered fully in English." },
    ],
    intakes: "September & March",
    popularCourses: ["Engineering", "Medicine (MBBS)", "Business", "Chinese Language", "Computer Science"],
    visa: "X1/X2 student visa via JW202 form — we guide admission and visa steps.",
    workRights: "Part-time work/internships permitted with university and visa approval.",
  },
];

export const getDestination = (slug: string) =>
  destinations.find((d) => d.slug === slug);
